---
- hosts: appserver
  user: ansible
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Get ACL information on the remote file
      acl: name=/etc/test.acl.txt entity=ansible etype=user permissions="rw" state=present
      register: aclinfo

    - debug:
        msg: var=aclinfo
   
