---
- hosts: aptserver
  user: ansible
  become: yes
  connection: ssh
  tasks:
    - name: Install Apache Web Server
      apt: name=apache2 state=present

    - name: Update system
      apt: update_cache=yes
