---
- hosts: aptserver
  user: ansible
  become: yes
  connection: ssh
  tasks:
    - name: Install Apache Web Server
      apt: name=apache2 state=present

    - name: Equivalent of update system
      apt: update_cache=yes

    - name: Equivalent of upgrade system
      apt: upgrade=dist 
   
