---
- hosts: appserver
  user: ansible
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Add a cron job to the ansible user
      cron: name="list files" minute="0" hour="1" job="ls -al > /home/ansible/cronresult.log"
