---
- hosts: appserver
  user: ansible
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Install web server
      yum: name=httpd state=installed

    - debug:
        msg: "Equivalent of sudo yum install httpd"

    - name: How long has the system been up?
      shell: /usr/bin/uptime
      register: result
    
    - debug:
        msg: "Uptime: {{ result }}"
