---
- hosts: appserver
  become: yes
  user: ansible
  gather_facts: yes
  connection: ssh
  tasks:
    - name: Run a remote ping on the appserver
      command: ping -c 4 "{{ ansible_hostname }}"
      delegate_to: 127.0.0.1

    - name: Install a package
      yum: pkg=elinks state=latest

    

