---
- hosts: appserver
  user: ansible
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Execute a command that will surely fail
      command: /bin/false
      ignore_errors: yes 
 
    - name: Install telnet package
      yum: pkg=telnet state=latest
