---
- hosts: appserver 
  user: ansible
  become: yes
  connection: ssh
  gather_facts: yes
  tasks:
    - name: Copy remote hosts file to control server
      fetch: src=/etc/hosts dest=/home/ansible/prefix-{{ ansible_hostname }} flat=yes

   
