---
- hosts: appserver
  user: ansible
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Get and download the INI file from the web server
      get_url: url=http://emgperez1.mylabserver.com/mytext.ini dest=/home/ansible/mytest.ini mode=0440 
