---
- hosts: single
  user: ansible
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Install the python dependencies
      apt: pkg=python-passlib state=latest

    - name: Adding a user to website authentication
      htpasswd: path=/etc/apache2/.htpasswd name=test2 password=pss owner=test2 group=test2 mode=0644
