---
- hosts: appserver
  become: yes
  vars:
    author_name: Ansible user
  vars_files:
    - vars.yml
  tasks:
    - name: Install elinks on App Servers
      yum: pkg=elinks state=installed update_cache=true
 
