---
- hosts: databases
  user: ansible
  become: yes
  connection: ssh
  gather_facts: no
  vars:
    playbook_version: 0.1b
  vars_files:
    - conf/copyright.yml
    - conf/webdefaults.yml
  vars_prompt:
    - name: pkg_name
      prompt: What package to install?
  
  tasks:
    - name: Install Apache Web Server
      action: yum name=httpd state=installed
      async: 300
      poll: 3
      notify: Restart HTTPD
      
    - name: Install {{ pkg_name }}
      action: yum name={{ pkg_name }} state=installed

  handlers:
    - name: Restart HTTPD
      service: name=httpd state=restarted
