---
- hosts: all
  become: yes
  tasks:

    - name: Install mysql server
      yum: name=mysql-server state=latest
      ignore_errors: yes
      register: mysql_there
      tags:
        - packages

    - name: start mysql service
      service: name=mysqld state=started
      register: mysql_start
      tags:
        - startup
    
