---
- hosts: appserver
  user: ansible
  become: yes
  connection: ssh
  gather_facts: no
  vars:
    - playbook_version: 0.01b
  vars_prompt:
    - name: packagetoinstall
      prompt: Which package to install?
      default: telnet
      private: no
     
  tasks:
    - name: Install the prompted package ({{ packagetoinstall }})
      yum: pkg={{ packagetoinstall }} state=latest
