---
- hosts: appserver
  become: yes
  user: ansible
  connection: ssh
  tasks:
    - name: Install web server
      action: yum name=httpd state=installed
     
    - name: Start web server
      service: name=httpd state=started

    - name: Enable httpd on reboot
      service: name=httpd enabled=yes
    
