---
- hosts: appserver
  user: ansible
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Install telnet
      yum: pkg=telnet state=latest

    - name: Install elinks
      yum: pkg=elinks state=latest

    - name: List home
      command: ls -al /home/ansible
      register: result
   
    - debug:
        msg: "Result: {{ result }}"
