---
- hosts: appserver
  become: yes
  user: ansible
  gather_facts: no
  tasks:
    - name: Install Apache Tomcat
      action: yum name=tomcat state=installed

    - name: Waiting for port 8080 to listen
      wait_for:
        port: 8080
        state: started

    - name: Verifying elinks installation
      action: yum name=elinks state=present 
