---
- hosts: appserver
  user: ansible
  become: yes
  connection: ssh
  vars:
    - playbook_type: conditionalexample
  vars_files:
    - conf/copyright.yml
    - conf/webdefaults.yml
  tasks:
    - name: Install Apache Appropriate to the distribution type
      #yum: pkg=httpd state=latest
      command: yum -y install httpd
      when: ansible_os_family == "RedHat"
