--- # Build and apache web server
- hosts: appserver
  user: ansible
  become: yes
  connection: ssh
  gather_facts: yes
  vars:
    apache_pkg: httpd
    distribution: "{{ ansible_os_family }}"
    apache_version: 2.4
    apache_dir: /var/www/sample
    apache_fqdn: emgperez6.mylabserver.com
  
  tasks:
    - name: Install the web server package
      yum: pkg={{ apache_pkg }} state=latest
     
    - name: Create the web server directory
      file: path={{ apache_dir }} state=directory mode=644

    - name: Copy the apache configuration file to the remote host
      copy: src=files/httpd.conf.template dest=/etc/httpd/conf owner=root group=root mode=644

    - name: Crate the VHOST.D directory on the remote host
      file: path=/etc/httpd/vhost.d state=directory mode=755

    - name: Copy and untar the source for the site
      unarchive: src=files/sitecode.tar.gz dest={{ apache_dir }} 

    - name: Copy the default vhost configuration file
      copy: src=files/default.conf.template dest=/etc/httpd/vhost.d/default.conf owner=root group=root mode=644
      notify: 
        - StartHTTPD
        - TestHTTPD
        - DisplayResult

  handlers:

    - name: StartHTTPD
      service: name={{ apache_pkg }} state=started
 
    - name: TestHTTPD
      shell: curl http://{{ apache_fqdn }}
      register: result
  
    - name: DisplayResults
      debug: var=result

  
  

