---
# handlers file for nfs.server
#
- name: StartServerServices
  service: name={{ item }} state=started
  with_items:
    - "{{ rpcbind_service }}"
    - "{{ nfsserver_service }}"
    - "{{ nfslock_service }}"
    - "{{ nfsmap_service }}"
