---
- hosts: appserver
  user: ansible
  become: yes
  connection: ssh
  gather_facts: yes
  vars:
    distribution: RedHat
    nfsutils_pkg: nfs-utils
    nfslibs_pkg: nfs-utils-lib
    nfsserver_service: nfs-server
    nfslock_service: nfs-lock
    nfsmap_service: nfs-idmap
    rpcbind_service: rpcbind
    export_path: /var/share  

  tasks:
    - name: Install all NFS server utilities, services and libraries
      yum: pkg={{ item }} state=latest
      with_items:
        - "{{ nfsutils_pkg }}"
        - "{{ nfslibs_pkg }}"
 
    - name: Copy the export file to remote server
      copy: src=files/exports.template dest=/etc/exports owner=root group=root mode=644
      notify:
        - StartServerServices
        - InstallClientPackages
        - CreateClientMountServerResource
        - ClientMountServerResource
        - TestServerAvailability

  handlers:
    - name: StartServerServices
      service: name={{ item }} state=started
      with_items:
        - "{{ rpcbind_service }}"
        - "{{ nfsserver_service }}"
        - "{{ nfslock_service }}"
        - "{{ nfsmap_service }}"


    # Delegations (that way I don't have to create another playbook with 'hosts: local' and the following tasks)
    - name: InstallClientPackages
      yum: pkg={{ item }} state=latest
      with_items:
        - "{{ nfsutils_pkg }}"
        - "{{ nfslibs_pkg }}"
      delegate_to: 127.0.0.1 # local
      notify: StartClientServices
    
    - name: StartClientServices
      service: name={{ item }} state=started
      with_items:
        - "{{ rpcbind_service }}"
        - "{{ nfslock_service }}"
        - "{{ nfsmap_service }}"
      delegate_to: 127.0.0.1

    - name: ClientMountServerResource
      mount: name=/mnt/remote src=/var/share fstype=nfs state=present
      register: result
      delegate_to: 127.0.0.1    

    - name: TestServerAvailability
      debug: var=result

    # End of delegations
   

     

   
